{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "apkzlib",
    "version": "4.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "zz53gouv6nfztoi24j3d3xklai"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "4.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "apkzlib-4.2.2.jar",
          "url": "apkzlib-4.2.2.jar",
          "size": 204415,
          "sha512": "840baf4e55976fcaf53afd594a09b5494abc454d875a150d534fa80087e4d775dc7af9cfa4ddda3cbe48d7963e9016de6e46f63e3ef7018a2194760585e84335",
          "sha256": "3b5167c1265e97f65201c4d2be6a6f72165a3aa2fe9e0594a59b67af9e9e97b9",
          "sha1": "9daf148c2e7e8b30e92d168fbaf092c1812452eb",
          "md5": "c6255f9c7ab7c62554e5416c7e5daef8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "4.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "apkzlib-4.2.2.jar",
          "url": "apkzlib-4.2.2.jar",
          "size": 204415,
          "sha512": "840baf4e55976fcaf53afd594a09b5494abc454d875a150d534fa80087e4d775dc7af9cfa4ddda3cbe48d7963e9016de6e46f63e3ef7018a2194760585e84335",
          "sha256": "3b5167c1265e97f65201c4d2be6a6f72165a3aa2fe9e0594a59b67af9e9e97b9",
          "sha1": "9daf148c2e7e8b30e92d168fbaf092c1812452eb",
          "md5": "c6255f9c7ab7c62554e5416c7e5daef8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "apkzlib-4.2.2-javadoc.jar",
          "url": "apkzlib-4.2.2-javadoc.jar",
          "size": 300653,
          "sha512": "f07954d5bc331bb0e6d371df3afe7c0b8569590962f063f1ef69db08a65b55b5ca93df6eb800da005c9e1c8ab4ec28f17cdf2d7fa3f48098e85f72ed54f572c6",
          "sha256": "457c5609ce31f80a747ebff54f3b2a1b00bac6c37fae40615b6dd06c878ad28b",
          "sha1": "22c8382e7d1c06509331ba939eab97a8cc2fbc2a",
          "md5": "f1e40459b57b36aaa9172980637ebc09"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "apkzlib-4.2.2-sources.jar",
          "url": "apkzlib-4.2.2-sources.jar",
          "size": 175631,
          "sha512": "97d5ae74ba1fe9a98567b91e451b1912a5dd5531e43004addf01cf66361dd69b992ba73e9333f8eca49720ea781535e1dd5e5de5748e95cae51e1bc801047f98",
          "sha256": "ba0dd6c1d238b5b90b56d265793f2e16ad75692a30c96a4748d5270000d882e8",
          "sha1": "003befc33bb6b1ef43435fcbe4b2b06ac9e220bc",
          "md5": "a95582bbc0bacf77e783a34b08ef0ec0"
        }
      ]
    }
  ]
}
