{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.flipper",
    "module": "flipper",
    "version": "0.125.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "flipper-0.125.0.aar",
          "url": "flipper-0.125.0.aar",
          "size": 10196604,
          "sha512": "9bf2e0ab1f2efb2665657bf7357868a006c7d508a9b460aa72513c8ee61c039fcb46498dc9b87a6568d49417f8a02c99b309f60863f16a8cb3fe484d01f1db5a",
          "sha256": "660fb19dd6a2e74c62f45723bbe6f2485c1e14ae204852f35432b57b1894f204",
          "sha1": "c12322c5857252fb083747a57e6dde55a0f68e2b",
          "md5": "6d199cadc9354a6311e312ec1fafa43a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.3"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "flipper-0.125.0.aar",
          "url": "flipper-0.125.0.aar",
          "size": 10196604,
          "sha512": "9bf2e0ab1f2efb2665657bf7357868a006c7d508a9b460aa72513c8ee61c039fcb46498dc9b87a6568d49417f8a02c99b309f60863f16a8cb3fe484d01f1db5a",
          "sha256": "660fb19dd6a2e74c62f45723bbe6f2485c1e14ae204852f35432b57b1894f204",
          "sha1": "c12322c5857252fb083747a57e6dde55a0f68e2b",
          "md5": "6d199cadc9354a6311e312ec1fafa43a"
        }
      ]
    }
  ]
}
