{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.fresco",
    "module": "fresco",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.facebook.fresco",
          "module": "fbcore",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "drawee",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-native",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "memory-type-ashmem",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "memory-type-native",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "memory-type-java",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "nativeimagefilters",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "nativeimagetranscoder",
          "version": {
            "requires": "2.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "fresco-2.6.0.aar",
          "url": "fresco-2.6.0.aar",
          "size": 52585,
          "sha512": "d75c28610e7b008ca37c4c80214819d65d799b789506e257de2a750ccbacfa7c059391c00c9adb33c1a7a6abb2ea9448cd47448e108b87d15f5ab69546e8e2a4",
          "sha256": "f0c94dfd29717ad0fc4bcf7f6b185e5fbce220c90abf59c63603872b39137647",
          "sha1": "46faf3dbac718a56365c24226660e55a22917c2c",
          "md5": "d164d6fe547ecbaf5b4ff4fb957f212d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.fresco",
          "module": "soloader",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "nativeloader",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "ui-common",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fbcore",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "drawee",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-native",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "memory-type-ashmem",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "memory-type-native",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "memory-type-java",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "nativeimagefilters",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "nativeimagetranscoder",
          "version": {
            "requires": "2.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "fresco-2.6.0.aar",
          "url": "fresco-2.6.0.aar",
          "size": 52585,
          "sha512": "d75c28610e7b008ca37c4c80214819d65d799b789506e257de2a750ccbacfa7c059391c00c9adb33c1a7a6abb2ea9448cd47448e108b87d15f5ab69546e8e2a4",
          "sha256": "f0c94dfd29717ad0fc4bcf7f6b185e5fbce220c90abf59c63603872b39137647",
          "sha1": "46faf3dbac718a56365c24226660e55a22917c2c",
          "md5": "d164d6fe547ecbaf5b4ff4fb957f212d"
        }
      ]
    }
  ]
}
