fastlane_version '2.211.0'

# before_all do
#   ensure_git_branch
#   ensure_git_status_clean
#   git_pull
# end

platform :ios do
   # iOS Lanes
   desc 'Build the iOS application.'

    private_lane :build do
        # certificates
        # increment_build_number(xcodeproj: './ios/name.xcodeproj')
        # gym(scheme: 'name', project: './ios/name.xcodeproj')
    end

    # desc 'Ship to Testflight.'
    # lane :beta do
    #     build
    #     pilot
    #     commit_version_bump(message: 'Bump build', xcodeproj: './ios/name.xcodeproj')
    #     push_to_git_remote
    # end
end

platform :android do
  # Android Lanes
end
