{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools",
    "module": "sdk-common",
    "version": "27.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "zz53gouv6nfztoi24j3d3xklai"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "27.2.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "27.2.2"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "shared",
          "version": {
            "requires": "27.2.2"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.jetbrains.intellij.deps",
          "module": "trove4j",
          "version": {
            "requires": "1.0.20181211"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "4.1.0-alpha01-6193524"
          }
        },
        {
          "group": "xerces",
          "module": "xercesImpl",
          "version": {
            "requires": "2.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-common-27.2.2.jar",
          "url": "sdk-common-27.2.2.jar",
          "size": 1638035,
          "sha512": "a30e0e0337165cef7b5a1c15beb78275176cba10a1c81c74d7e1dbe3e927c41342e66bf10bd5dcddc140999023c772a07da7c02a7df837c3f0d3c107c2efbbf7",
          "sha256": "b147acc13850808d61fc391ccfeeebdf90841b461a7042acb2d92e466da8e674",
          "sha1": "92b58de5b4904f946ec7d9588d7f952bd60364de",
          "md5": "99aa3c0eece40e045170f98379f2c54c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "27.2.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "27.2.2"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "shared",
          "version": {
            "requires": "27.2.2"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.jetbrains.intellij.deps",
          "module": "trove4j",
          "version": {
            "requires": "1.0.20181211"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "4.1.0-alpha01-6193524"
          }
        },
        {
          "group": "xerces",
          "module": "xercesImpl",
          "version": {
            "requires": "2.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-common-27.2.2.jar",
          "url": "sdk-common-27.2.2.jar",
          "size": 1638035,
          "sha512": "a30e0e0337165cef7b5a1c15beb78275176cba10a1c81c74d7e1dbe3e927c41342e66bf10bd5dcddc140999023c772a07da7c02a7df837c3f0d3c107c2efbbf7",
          "sha256": "b147acc13850808d61fc391ccfeeebdf90841b461a7042acb2d92e466da8e674",
          "sha1": "92b58de5b4904f946ec7d9588d7f952bd60364de",
          "md5": "99aa3c0eece40e045170f98379f2c54c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-common-27.2.2-javadoc.jar",
          "url": "sdk-common-27.2.2-javadoc.jar",
          "size": 929401,
          "sha512": "2de2b82b0aa753942e4cc09ec1cf30b39125497b1539da4aa28c3144326442bcf0c397fb808a46afcdd59d3d5c247664757ea205fe8919a95be037547613cb72",
          "sha256": "605c22e3926bc9fa97e7d40998db188963d9ff17f93c2d5310bd4b9c38115b66",
          "sha1": "668536525c5638ae8d1ffd534ef14c7f9bb4d9b8",
          "md5": "fdf4bb2c040fc4f94efcdc2d0594f49d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-common-27.2.2-sources.jar",
          "url": "sdk-common-27.2.2-sources.jar",
          "size": 814786,
          "sha512": "aa2badb5a1dc1bca7ef87c78d4c3679c5a6a2eb41e7d5558416a5c6db3f21177601eed7f7bbab43b885bb471f5109d7d6f9883f0610a11b789682a98fbb77d7a",
          "sha256": "2a47e0e6bda86697f8e2dd095de7e36d4fdacb4ba7f4858ffc73cd893c16970b",
          "sha1": "58f25f54f3abbe340a62a572d6032c44b0bf95f6",
          "md5": "d9229cd1e3f6d8d7a5b9f3647850ab5d"
        }
      ]
    }
  ]
}
