{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appcompat",
    "module": "appcompat-resources",
    "version": "1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.4.1.aar",
          "url": "appcompat-resources-1.4.1.aar",
          "size": 67071,
          "sha512": "dd512ea62da31a6f8f9cef72680a2582c7a5ffaf0ee3e54ffd21a9a0b2ce6c1c4b703f04c92830a37f79babc78440fa214b440ce84aac086bec0d17d3dd117ba",
          "sha256": "c324f0a157e3cf2decd8448107de487420cb4f4fb4853cd634d71ec1f2226224",
          "sha1": "527d93d44bb18bc7dcf5213df8d4d069f0ceff61",
          "md5": "d0c265f75a956920a45e125fde6f1e1d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.4.1.aar",
          "url": "appcompat-resources-1.4.1.aar",
          "size": 67071,
          "sha512": "dd512ea62da31a6f8f9cef72680a2582c7a5ffaf0ee3e54ffd21a9a0b2ce6c1c4b703f04c92830a37f79babc78440fa214b440ce84aac086bec0d17d3dd117ba",
          "sha256": "c324f0a157e3cf2decd8448107de487420cb4f4fb4853cd634d71ec1f2226224",
          "sha1": "527d93d44bb18bc7dcf5213df8d4d069f0ceff61",
          "md5": "d0c265f75a956920a45e125fde6f1e1d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "appcompat-resources-1.4.1-sources.jar",
          "url": "appcompat-resources-1.4.1-sources.jar",
          "size": 40855,
          "sha512": "6dbc472b68da1cf1e7c08973d9f796881ca59ab21bc922580d3ca8b07b206a50e07d9751cfc802d580cff5d08aa2f7dd84061cd090397328d14f090d2bc184bf",
          "sha256": "014980c366a1755d486e4cde2ea616cc2074963c5f48ffcb01dee15dd5f9421d",
          "sha1": "8f78838745a125dea62514f7b4f70e8776a6244e",
          "md5": "4e8141afafcbf7ffe9e19ec02207f2e0"
        }
      ]
    }
  ]
}
